CREATE TABLE IF NOT EXISTS Authors (Name VARCHAR(100) PRIMARY KEY NOT NULL, NumOfPubl INTEGER, NumOfCoAuth INTEGER,
AuthorID INTEGER);
CREATE TABLE IF NOT EXISTS Publications (AuthorID INTEGER PRIMARY KEY, Title VARCHAR(100) NOT NULL,
NumOfAuth INTEGER, PublVenID, INTEGER);
CREATE TABLE IF NOT EXISTS Venues (PublVenID INTEGER PRIMARY KEY, Name VARCHAR(100) NOT NULL, YearOfOcc YEAR);